RMSW-78
RensselaerMotorsport/VehicleControlUnit pull request #15
Opened 2024-09-27 22:33 UTC by tiffcmw

Added code for converting and storing ADC values from analog sensors. 

Added the following GPIO PINS in .ioc:
PA3: USART2_RX
PD5: USART2_TX
PA4: ADCI_IN4 (Channel 4)
PA5: ADC1_IN5 (Channel 5)
PC8: GPIO_Output
PC9: GPIO_Output
PC10: GPIO_Input
PC11: GPIO_Input

Key Changes: 
1. Circular Buffer Implementation:
- A circular buffer (adc_circular_buffer) is used to store ADC samples.
- Functions like addSampleToBuffer, getLatestSample, and getRecentSamples manage this buffer.

2. ADC Data Processing:
- The ProcessADCData function processes ADC data for channels 4 and 5 (PA4 and PA5 respectively).
- It stores the data in the circular buffer and optionally sends debug information via UART.

3. Data Retrieval:
- getAnalogSensorData retrieves the latest data for a specific sensor (currently only supports channels 4 and 5).

The code has only been tested in a private project. Further testing has to be made depending on the actual input and output sources in the car's system.

2024-09-27 23:03 UTC, AmarMaksumic requested changes
Code is very good! Let's just implement all the channels now and do some cleanup with variable names and logic~ Thank you!

2024-09-27 23:03 UTC, AmarMaksumic commented on Core/Src/main.c
> +  /*Configure GPIO pin Output Level */
Remove this so it doesnt confuse others

2024-09-27 23:50 UTC, Arct1cPharaoh requested changes
One small detail. Other than that lgtm

2024-09-27 23:50 UTC, Arct1cPharaoh commented on Core/Src/Sensors/AnalogSensor.c
> +    } else {
Since you return in the if statement you could just not have an else statement.

2024-09-29 01:23 UTC, AmarMaksumic reviewed
LGTM, only question is did you test all three ADCs outside of this code?

2024-09-29 01:33 UTC, Arct1cPharaoh approved these changes
lgtm. Good work!

2024-09-30 15:22 UTC, AmarMaksumic approved these changes
Tiffany tested code, made sure all three ADCs can work at same time. Approved!

2024-09-30 23:50 UTC, merged